name: stylish

on:
  pull_request:
  workflow_dispatch:

jobs:
  stylish:
    name: "black & flake8 & ruff & rpmlint"
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - name: Install testing packages
      run: |
        dnf --setopt install_weak_deps=False install -y \
            git-core \
            python3-flake8 \
            python3-pip \
            rpmlint
        python3 -m pip install --upgrade pip wheel
        python3 -m pip install ruff

    - uses: actions/checkout@v3

    - uses: psf/black@stable
      with:
        version: "23.3.0"

    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1

    - name: Run flake8
      run: |
        flake8

    - name: Run ruff
      run: |
        ruff src/ test/

    - name: Run rpmlint
      run: |
        rpmlint subscription-manager.spec
